deploy:
  provider: pages
  skip-cleanup: true
  github-token:   # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: public
  repo: Westfriesland/westfriesland.github.io
  target_branch: master

